"""The application protocol: what the client and the server agree on.

The client sends one request message: the number of bytes it wants, as an 8-byte
unsigned integer in network byte order. The server answers with one message that
contains exactly that many bytes, generated by make_data(), so that the client can
check that what it received is correct.

Both messages go through the transport protocol of protocol.py, never directly
through the UDP socket.
"""
import argparse
import struct

from protocol import DEFAULT_WINDOW, PROTOCOLS

PORT = 20003
REQUEST = struct.Struct("!Q")

# 251 is prime: a segment delivered at the wrong position, twice or not at all
# makes the received data different from the expected one.
PATTERN = bytes(range(251))


def make_data(size):
  """The `size` bytes the server sends back for a request of `size` bytes."""
  return (PATTERN * (size // len(PATTERN) + 1))[:size]


def add_transport_arguments(parser: argparse.ArgumentParser):
  parser.add_argument("--protocol", choices=PROTOCOLS, default="stopwait",
                      help="transport protocol (default: stopwait)")
  parser.add_argument("--window", type=int, default=DEFAULT_WINDOW,
                      help=f"window size, in segments (default: {DEFAULT_WINDOW})")
  parser.add_argument("--port", type=int, default=PORT, help=f"server port (default: {PORT})")
